### ISSUE TITLE
How can install the language on Mac OS?

### ISSUE THREAD

**Issue by giacomomarchioro** [ryanfb/latinocr-lattraining#5]
Hi, 
I can't find the documentation and how I can install this language package using tessearct on OSX operating system.

Can you please give me some instructions?

Thank you!
Giacomo

**Comment by ryanfb** [comment]
If you use [Homebrew](https://brew.sh/), `brew install --all-languages tesseract` should now come with a version of the Latin OCR training file. Or you can copy a specific `lat.traineddata` file into `/usr/local/share/tessdata` after using `brew install tesseract`.
